project:
  type: website
  output-dir: docs    # GitHub Pages looks in the /docs folder

website:
  title: "Mini-project: Interactive Analysis"
  navbar:
    left:
      - href: 3dstructures.qmd
        text: 3D Structures
      - href: structural_metrics.qmd
        text: Structural Metrics

format:
  html:
    theme: cosmo
    self-contained: true  # Keeps dependencies bundled